### ISSUE TITLE
Develop a fully-tested crypto API

### ISSUE THREAD

**Issue by oegea** [oegea/passager-password-manager#33]
**Notice**

I know that this is not a conventional user story, and that technical-only issues should not (in theory) be created, at least from the product perspective, because it doesn't bring value to end user.

However, I'll be working on this during the following days, before moving to encrypting folders. I think that first, and before implementing more methods that rely on the crypto api, we need to have a solid foundation. That's why this issue exists.

We need to put all our efforts to ensure a safe environment when using Passager. That's why I think this needs an specific issue and detailed follow-up.

**Goal**

Write a fully library that performs basic crypto operations, wrapping the crypto web API and making its usage easier.

Although crypto web API is not a hard-to-use API, the most important detail is to correctly use the required crypto algorithms, avoiding or trying to avoid security faults. 

Methods detailed here respond to the following plan:

1. Each user will have an RSA key pair. Public key of a user will be publicly readable, private key will be secured in database-level, but also wrapped and encrypted with an AES key, derivated from the user's master password.
2. Each password folder will encrypt all its passwords simetrically, with an AES key.
3. These AES keys will be secured in a database-level, only readable for the owner, but also asimetrically encrypted with user's public key.
4. Users will decrypt these folder's keys by using their private keys, and then decrypt passwords with the specific simmetric folder key, decrypted on the previous task.

**Tasks**

All tasks assume that functional tests are part of the DoD.

* [x] Read and learn more about cryptography (start here https://www.crypto101.io/ and maybe advance with a book more focused on javascript)
* [x] Method to create an AES key from a passphrase.
* [x] Method to encrypt data  using an AES key.
* [x] Method to decrypt data using an AES key.
* [x] Method to simmetrically encrypt data using a passphrase (wrapping tasks 1 and 2 into one method).
* [x] Method to simmetrically decrypt data using a passphrase (wrapping tasks 1 and 3 into one method).
* [x] Method to randomly generate an AES key.
* [x] Method to randomly generate an RSA key-pair.
* [x] Method to asimetrically wrap and export an AES key.
* [x] Method to asimetrically unwrap and import an AES key.
* [x] Method to wrap an RSA private key.
* [x] Method to unwrap an RSA private key.
* [x] Method to asimetrically encrypt data using an RSA public key.
* [x] Method to asimetrically decrypt data using an RSA private key.
* [x] Try to get these methods audited by someone experienced in cryptography.
